In [ ]:
import random
Lst= ['Python', 23,67.9, 'true']
R=random.choice(Lst)
print(R)

true


In [ ]:
import random
Alpha=[]
for i in range(ord('A') , ord('Z') +1):
    Alpha.append(chr(i))

lower=[]
for i in range(ord('a'), ord('z')+1):
    lower.append(chr(i))

symbols=['@','&','/','!','$']

Numbers=[1,2,3,4,5,6,7,8,9,0]

List =Alpha + lower + symbols + Numbers
print(List)

n=int(input("Enter the length of password"))

for i in range(n+1) :
    R+=str(random.choice(List))

print(f"Password generated is: {R}")

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '@', '&', '/', '!', '$', 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


KeyboardInterrupt: Interrupted by user

In [ ]:
def place_order(customer_name, food_item, quantityprice):
  item={}
  total_price=0
  customer_name=input("Enter Customer Name: ")
  n=int(input("Enter the number of items bought: "))
  for i in range(n):
    food_item=input("Enter the name of food item: ")
    item.update({food_item : quantityprice})
    quantityprice=int(input("Enter the price of item: "))
    total_price+=quantityprice

  print("\n---Order Invoice---")
  print("Customer name:",customer_name)
  print(item)
  print(f"Total price of the items bought: {total_price}")

place_order(customer_name='',food_item='',quantityprice=0)



In [ ]:
l=[]
n=int(input('enter number of items to enter'))
for i in range(n):
  obj=input("enter the name of obj: ")
  l.append(obj)
print(l)

In [ ]:
import random
game =['Rock', 'Paper', 'Scissors']
you=input("enter your choice").capitalize()
p1=random.choice(game).capitalize()
y=0
p=0
n=int(input("How many rounds of match: "))
for i in range(n):
  if(you==p1):
    print("Tie")
  elif((you=='Rock' and p1=='Scissors')or (you=='Scissors' and p1=='Paper')or (you=='Paper' and p1=='Rock')):
    print("Point to You")
    y+=1
  elif((p1=='Rock' and you=='Scissors')or (p1=='Scissors' and you=='Paper')or (p1=='Paper' and you=='Rock')):
    print("Point to p1")
    p1+=1

if(p>y):
  print(f'YOu ARE THE WINNER WITH POINTS {y}')

elif(p<y):
  print(f'P1 IS THE WINNER WITH POINTS {p}')

In [ ]:
class rectangle: #class
  def __init__(self,length,width):  #constructor
    self.length = length
    self.width = width

  def Area(self):  #object : replica to call the methods of the class or to implement or access it
    area = self.length * self.width
    return area

  def perimeter(self):
    per = 2*(self.length + self.width)
    return per

rec = rectangle(2,4)
print(rec.Area())
print(rec.perimeter())

In [ ]:
# number guessing game
import random
ch=0
def user_choice():
  ch=int(input("Enter your choice:[1 OR 2 OR 3]"))
  if(ch==1):
    print("You're at easy level\nATTEMPTS : 5")
  elif(ch==2):
    print("You're at medium level\nATTEMPTS : 7")
  elif(ch==3):
    print("You're at hard level\nATTEMPTS : 10")
  else:
    print("can't you see the instructions")
  return ch

def num_guess():
  ch=user_choice()
  if(ch==1):
    max_attempt=5
    max_num = 10
  elif(ch==2):
    max_attempt=7
    max_num=50
  elif(ch==3):
    max_attempt=10
    max_num=100
  else:
    print('Wrong choice exiting the game')
    exit()
  for i in range(max_attempt):
    num=random.randint(1,11)
    guess=int(input("Guess the number :"))
    print("Random number is: ",num)
    max_attempt=max_attempt-1
    if(num==guess):
      print("You GUESSED THE NUMBER CORRECT")
      break
    elif(num>guess):
      print('TOO LOW! Try Again Mate\n''attempts remaining',max_attempt)
    elif(num<guess):
      print('TOO HIGH! Try Again Mate\n''attempts remaining',max_attempt)
    else:
      print('attempts remaining',max_attempt)
    if(max_attempt==0):
      print('Game Over! The correct number was:',num)
while(1):
  print("number guess game")
  num_guess()
  choice=input("Do you want to try again?\nenter your choice: [Y/N] ")
  if(choice in ('Y', 'y')):
    num_guess()
  else:
    break


In [ ]:
# bank system
'''
1. current value - pin
2. deposit - enter pin
3. withdraw - enter you pin
4. change pin - enter new pin
'''
print("ENTER THE ACC. NO.: ")
class ATM:
  def machine():




In [ ]:
from datetime import datetime, date
def vehicle():
  owner=input("Enter your name:")
  vehicle = input("Enter the vehicle number: ")
  now = datetime.now()
  print("Vehicle entry at: ",now)

  return(owner,vehicle,now)

def customer():
  customer = {'Sudhir': ('UP 32 DD 8990', 750),'Sameer': ('UP 32 NP 4590', 500),'Divyanka': ('UP 42 KK 0101', 1000)}
  print('OWNER\t\tVEHICLE\t\tBALANCE')
  print('-' * 45)
  for owner, (vehicle, balance) in customer.items():
      print(f"{owner:<10}{vehicle:<15}{balance:<10}")
  cust=input("If you're a regular/new custome: ")
  if(cust in ('new', 'NEW', 'New')):
    vehicle()
    temp_database()
  elif(cust in ('regular', 'Regular', 'REGULAR')):
    print('enter your name: ')
    if (owner in customer):
      print('found: ',data(owner))

def parking():
  print("NS2 WELCOMES YOU DO PARK YOUR VEHICLE MATE")
  customer()

def payment():
  print("")


def temp_database():
  temp_data = {}
  temp_data.update({owner : (vehicle,balance)})
  print('')

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
'''print(arr[0])'''
print(arr>40)
print(arr[arr>40])

[False False False False False False]
[]


In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
arr2=np.array([[45,78,69,47,37],[57,32,90,12,90]])
arr3=np.array([[[30,40,53,90,32],[56,87,9,23,56]],
 [[90,44,56,23,78],[34,67,89,64,32]]])
'''print('arr= ',arr)
print('\narr2=',arr2)
print('\narr3=',arr3)'''
#print(arr[2:3])
#print(arr2[0:2,3:5])
print(arr3[:4, :4, :4])
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

[[[30 40 53 90]
  [56 87  9 23]]

 [[90 44 56 23]
  [34 67 89 64]]]
(2, 2, 5)
3
20


In [ ]:
import pandas as pd

# Create a sample DataFrame
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami'],
    'Score': [85, 92, 78, 95, 88]
}, index=['row1', 'row2', 'row3', 'row4', 'row5'])

print("Sample DataFrame:")
display(df)

In [ ]:
'''from datetime import datetime, date
current_now = datetime.now()
print(current_now)'''
data={'Sudhir': ('UP 32 DD 8990', 750), 'Sanjay':('UP 32 NP 4590', 500)}
print(data)

{'Sudhir': ('UP 32 DD 8990', 750), 'Sanjay': ('UP 32 NP 4590', 500)}


In [ ]:
import pandas as p
data = p.Series([10,20,30])
print(data)

0    10
1    20
2    30
dtype: int64


In [ ]:
import pandas as pd
data = p.Series({1:'Utkarsh', 2: "aksh", 3:'Shishir'})
print(data)

1    Utkarsh
2       aksh
3    Shishir
dtype: object


In [ ]:
import pandas as pd
data ={'name':['Utkarsh', "aksh",'Shishir'],
       'age': [12,56,23]}
d=pd.DataFrame(data)
print(d)

      name  age
0  Utkarsh   12
1     aksh   56
2  Shishir   23


In [ ]:
import pandas as pd
data = [
    {"Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Paris", "Tokyo"]
}]
df = pd.DataFrame(data)
print(df)

                    Name           Age                      City
0  [Alice, Bob, Charlie]  [25, 30, 35]  [New York, Paris, Tokyo]


embarked
data.dropna(
  aixs =0
  how =''
  subnet='none'
  inplace = 'true' or 'false'
data.dropna(data[embarked])

fillna()

data['ag']=data['ag'].fillna(data['ag'].mean())

forward fill
backward fill


q- series dsa using pandas[list & dict]
q- dataframe using pandas [list and dict]

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(d)
print(type(d))
print(d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [ ]:
# higher dimensional array
import numpy as np

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [ ]:
# accessing elements form arrays
# 1D array

import numpy as np

arr = np.array([1,2,4])
print(arr[0])

#2D
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

#3D
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,1])

#neagtive indexing
arr = np.array([[1,3,4,5,6],[4,6,7,8,9]])
print(arr[1,-4])

1
6
11
6


In [ ]:
import zipfile

with zipfile.ZipFile('/content/titanic.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

In [2]:

from google.colab import userdata
import subprocess
import os

# Read the token from Colab Secrets
token = userdata.get("GITHUB_TOKEN")

credential = (
    f"protocol=https\n"
    f"host=github.com\n"
    f"username=shishirbuilds\n"
    f"password={token}\n\n"
)

subprocess.run(
    ["git", "credential", "approve"],
    input=credential,
    text=True,
    check=True
)

# Set your Git author identity
subprocess.run(
    ["git", "config", "--global", "user.name",
     "shishirbuilds"],
    check=True
)

# Use an email associated with your GitHub account
subprocess.run(
    ["git", "config", "--global", "user.email",
     "singhshishir156@mail.com"],
    check=True
)

# Clone your repository
repo_url = ('https://github.com/shishirbuilds/Machine-Learning-.git')

subprocess.run(["git", "clone", repo_url], check=True)

print("GitHub authentication and repository setup complete.")

GitHub authentication and repository setup complete.


In [3]:
subprocess.run(
    ["git", "config", "--global", "credential.helper", "store"],
    check=True
)

CompletedProcess(args=['git', 'config', '--global', 'credential.helper', 'store'], returncode=0)

In [6]:
!find /content/drive/MyDrive -name "*SIC.ipynb"

find: ‘/content/drive/MyDrive’: No such file or directory


SyntaxError: invalid syntax (3138603008.py, line 1)